import streamlit as st
import pandas as pd
import numpy as np 
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go
df=pd.read_csv('A.csv')
df1=pd.read_csv('B.csv')
df2=pd.read_csv('C.csv')
df3=pd.read_csv('Renewable Electricity Capacity by State_D_20210426_203204.csv')
df4=pd.read_csv('Electricity Potential by Energy Source_D_20210427_132109.csv')
df5=pd.read_csv('Electricity Potential by State_D_20210427_131321.csv')
df6=pd.read_csv('Electricity Capacity by State_D_20210427_143749.csv')
df7=pd.read_csv('Electricity Capacity by Energy Source_D_20210427_143811.csv')
st.sidebar.title("Energy")
visualization = st.sidebar.selectbox('Select a type',('Potential','Generation','Capacity'))
select_chart = st.sidebar.selectbox('Select a Chart',('Bar Chart','Bubble Chart','Pie'))
st.markdown('''
    <div class="jumbotron text-center" style='background-color: #fff'>
    <h1 style="margin: auto; width: 100%;">Current Energy Scenario in India</h1>
 
 
    </div>
''', unsafe_allow_html=True);
if visualization=='Generation':
  
 
  st.markdown("## **State wise Electricity Generation via Renewables**")
  state_select = st.selectbox('Select a state',df['State'].unique())
  
  selected_state = df[df['State']==state_select]
  if select_chart=='Bar Chart':
    a=px.bar(selected_state,x='YearValue',y='Generation_GWh',color='EnergySource',barmode='group')
    st.plotly_chart(a)
  elif select_chart=='Bubble Chart':
    Bubble=px.scatter(selected_state, x='YearValue', y='Generation_GWh',
	         size="Generation_GWh", color='EnergySource',size_max=60)
    st.plotly_chart(Bubble)
  elif select_chart=='Pie':
    a=px.pie(selected_state, values='Generation_GWh', names='EnergySource')
    st.plotly_chart(a)
	
	
  st.markdown("## **Generation of Electricity By Energy Source**")
  energy_select=st.radio('Select a Energy Type',df1['EnergySourceType'].unique())
  energy=df1[df1['EnergySourceType']==energy_select]
  if select_chart=='Bar Chart':
    b=px.bar(energy,x='YearValue',y='Generation_GWh',color='EnergySource',barmode='group')
    st.plotly_chart(b)
  elif select_chart=='Bubble Chart':
    Bubble=px.scatter(energy, x='YearValue', y='Generation_GWh',
	         size="Generation_GWh", color='EnergySource',size_max=60)
    st.plotly_chart(Bubble)
  elif select_chart=='Pie':
    a=px.pie(energy, values='Generation_GWh', names='EnergySource')
    st.plotly_chart(a)
	
	
  st.markdown("## **Total Electricity Generated by State**")
  state = st.selectbox('Select state',df2['State'].unique())
  selected = df2[df2['State']==state]
  if select_chart=='Bar Chart':
    c=px.bar(selected,x='YearValue',y='Generation_GWh')
    st.plotly_chart(c)
  elif select_chart=='Bubble Chart':
    c=px.scatter(selected,x='YearValue',y='Generation_GWh',size="Generation_GWh",size_max=60)
    st.plotly_chart(c)
  elif select_chart=='Pie':
    a=px.pie(selected, values='Generation_GWh', names='YearValue')
    st.plotly_chart(a)	
	
	
elif visualization=='Capacity':
  st.markdown("## **Installed Capacity by State**")
  state_select = st.selectbox('Select a state',df3['State'].unique())
  selected_state = df3[df3['State']==state_select]
  if select_chart=='Bar Chart':
    a=px.bar(selected_state,x='YearValue',y='Capacity_MW',color='EnergySource',barmode='group')
    st.plotly_chart(a)
  elif select_chart=='Bubble Chart':
    a=px.scatter(selected_state,x='YearValue',y='Capacity_MW',size="Capacity_MW",color='EnergySource',size_max=60)
    st.plotly_chart(a)
  elif select_chart=='Pie':
    a=px.pie(selected_state, values='Capacity_MW', names='YearValue')
    st.plotly_chart(a)	
	
	
  st.markdown("## **Installed Capacity by Energy Source**")
  energy_select=st.radio('Select a Energy Type',df7['EnergySourceType'].unique())
  energy=df7[df7['EnergySourceType']==energy_select]
  if select_chart=='Bar Chart':
    b=px.bar(energy,x='YearValue',y='Capacity_MW',color='EnergySource',barmode='group')
    st.plotly_chart(b)
  elif select_chart=='Bubble Chart':
    b=px.scatter(energy,x='YearValue',y='Capacity_MW',size="Capacity_MW",color='EnergySource',size_max=60)
    st.plotly_chart(b)
  elif select_chart=='Pie':
    a=px.pie(energy, values='Capacity_MW', names='YearValue')
    st.plotly_chart(a)	  
	
	
elif visualization=='Potential': 
  st.markdown("## **State Wise Potential **")
  state = st.selectbox('Select state',df5['State'].unique())
  selected = df5[df5['State']==state]
  if select_chart=='Bar Chart':
    c=px.bar(selected,x='YearValue',y='CapacityIdentified_MW')
    st.plotly_chart(c)
  elif select_chart=='Bubble Chart':
    b=px.scatter(selected,x='YearValue',y='CapacityIdentified_MW',size="CapacityIdentified_MW",size_max=60)
    st.plotly_chart(b)
  elif select_chart=='Pie':
    a=px.pie(selected, values='CapacityIdentified_MW', names='YearValue')
    st.plotly_chart(a)
	
  st.markdown("## **Energy Source Wise Potential**")
  energy_select=st.radio('Select a Energy Type',df4['EnergySourceType'].unique())
  energy=df4[df4['EnergySourceType']==energy_select]
  if select_chart=='Bar Chart':
    b=px.bar(energy,x='YearValue',y='CapacityIdentified_MW',color='EnergySource',barmode='group')
    st.plotly_chart(b)
  elif select_chart=='Bubble Chart':
    b=px.scatter(energy,x='YearValue',y='CapacityIdentified_MW',size="CapacityIdentified_MW",color='EnergySource',size_max=60)
    st.plotly_chart(b)
  elif select_chart=='Pie':
    a=px.pie(energy, values='CapacityIdentified_MW', names='YearValue')
    st.plotly_chart(a)
